spring:
  datasource:
    driver-class-name: org.h2.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    spring-flyway-baseline-on-migrate: true
    spring-flyway-baseline-version: 0
