spring:
  show-sql: true
  format_sql: true
  datasource:
    driver-class-name: org.h2.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: ${ DATASOURCE_URL }
    username: ${ DATASOURCE_USERNAME }
    password: ${ DATASOURCE_PASSWORD }
    spring-flyway-baseline-on-migrate: true
    spring-flyway-baseline-version: 0

  data:
    web:
      pageable:
        page-parameter: pagina
        size-parameter: tamanho
      sort:
        sort-parameter: ordem
server:
  error:
    include-stacktrace: never

api:
  security:
    token:
      secret: ${JWT_SECRET:12345678}
